services:
  - type: web
    name: linkedin-profile-api
    runtime: docker
    plan: free
    envVars:
      - key: LINKEDIN_EMAIL
        sync: false
      - key: LINKEDIN_PASSWORD
        sync: false
